repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-case-conflict
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: fix-byte-order-marker

  - repo: https://gitlab.com/jvenom/elixir-pre-commit-hooks
    rev: v1.2.0 # replace with the version you want to use
    hooks: # specify the hooks you want to use here
      - id: mix-format
